### ISSUE TITLE
Allow CORS for mycollectibles.io

### ISSUE THREAD

**Issue by TimDaub** [ENS-Nifty/ens-nifty-backend#1]
Hi,

I'm the author of an open source ERC721 wallet called https://mycollectibles.io. I tried running it with an ENSNifty token and it works except for fetching the data from ensnifty.com's backend because there is an issue with CORS.

<img width="1438" alt="screen shot 2018-11-02 at 13 02 46" src="https://user-images.githubusercontent.com/2758453/47925731-27a45100-debf-11e8-9878-f5819fc5dff8.png">

It would be nice if you could allow my website to request yours so that users can see their ensnifties on mycollectibles.io. To test how it works, simply connect with Metamask on the site, then click "Add Token" after the loading screen and enter ensnifty's contract address. It should then proceed to load your ERC721s.

**Comment by pedrouid** [comment]
cc @sudoryan

**Comment by sudoryan** [comment]
Hi @TimDaub , 

Thanks for the issue. I've just added the {'Access-Control-Allow-Origin': '*'} header to the metadata response. 

After the update I went to your website and tried loading my ENSNifty token and in the console I'm not getting the CORS error but instead I'm getting:

![image](https://user-images.githubusercontent.com/23408540/47970895-1df62700-e040-11e8-9d37-9b1ef36a03d0.png)

The page then says 'No collectibles found'.

**Comment by TimDaub** [comment]
Hi, you get that error when `tokens` in localStorage is empty. To add a token, click "Add Token" and fill in "0x7c523c42ad255e5b270b12fee2ecc1103e88a9dc" to add the ENSNifty token.

<img width="274" alt="screen shot 2018-11-05 at 09 39 03" src="https://user-images.githubusercontent.com/2758453/47987010-a6c3a000-e0de-11e8-97b3-455e0aa0b01f.png">

The request now works, thank you very much! 🎉
